### ISSUE TITLE
Install on python 3 with pip 10.0.1 fails

### ISSUE THREAD

**Issue by oldium** [pycontribs/wstools#21]
Hi, when I try to install the wstools-py3 module on python 3.6.5 with pip 10.0.1, I got the following error:

```
  Using cached https://files.pythonhosted.org/packages/c7/6f/db5e44de413183388a5a6b261b35e2fbda38081f42be2fabf6e30b49bc11/wstools-py3-0.54.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\oldium\AppData\Local\Temp\pip-install-eiq3gpnx\wstools-py3\setup.py", line 10, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```

According to pip [release notes](https://pip.pypa.io/en/stable/news/), the pip.req module moved to pip._internal.req to show that there is no public API - this is since pip 10.0.0b2.

**Comment by oldium** [comment]
Ah, wrong package - this is about wstools-py3, which has wrong home page on PyPi... Should be at [https://github.com/Synerty/wstools-py3](https://github.com/Synerty/wstools-py3) most probably...
