### ISSUE TITLE
Unable to build 0.4.4

### ISSUE THREAD

**Issue by cdonati** [pycontribs/wstools#8]
I'm unable to build the latest PyPI release (wstools-0.4.4.tar.gz) with `python setup.py install`:

```
...
Installed ...wstools-0.4.4/.eggs/pytest_timeout-1.0.0-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 168, in <module>
    'Topic :: Internet :: WWW/HTTP',
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "...site-packages/setuptools/dist.py", line 348, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "...site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
    replace_conflicting=True,
  File "...site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application
```

As far as I can tell, the `PyTest` class definition in `setup.py` is causing some conflict. If I rename the class and later reference to something like `PyTest2`, the installation works.

**Comment by ssbarnea** [comment]
Please try the `develop` branch and see if this works for you. Also please provide full information regarding on which operating system and python version you encountered this. If you can also test with multiple versions it would be even better.

**Comment by gracinet** [comment]
Hi, I can reproduce with a fresh Python 2 virtualenv under Debian 8.
Commands:
```
demo@localhost:/tmp$ wget https://pypi.python.org/packages/e3/5c/ce1fa20a429f7e65216e7becc18b145091c23600667e979b14f6dca7c924/wstools-0.4.4.tar.gz#md5=cb7c2a759aedc7c6a4e5a235d9b0e950
demo@localhost:/tmp$ virtualenv testenvwstools
Running virtualenv with interpreter /usr/bin/python2
New python executable in testenvwstools/bin/python2
Also creating executable in testenvwstools/bin/python
Installing setuptools, pip...done.
demo@localhost:/tmp$ testenvwstools/bin/pip install wstools-0.4.4.tar.gz
```

Our initial encounter with this issue was in zc.buildout context. Also, a simple pip would work for install, but that's because it'd use the wheel.

[Full pip log](https://github.com/pycontribs/wstools/files/381650/pip.log.txt)

**Comment by gracinet** [comment]
The problem does not seem to be there with the develop branch (if I tested it right):

```
demo@localhost:/tmp$ virtualenv /tmp/testenvwstools-develop
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/testenvwstools-develop/bin/python2
Also creating executable in /tmp/testenvwstools-develop/bin/python
Installing setuptools, pip...done.
demo@localhost:/tmp$ /tmp/testenvwstools-develop/bin/pip install git+https://github.com/pycontribs/wstools@develop#egg=wstools
Downloading/unpacking wstools from git+https://github.com/pycontribs/wstools@develop
  Cloning https://github.com/pycontribs/wstools (to develop) to ./pip-build-_PPYhP/wstools
  Running setup.py (path:/tmp/pip-build-_PPYhP/wstools/setup.py) egg_info for package wstools
    
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./testenvwstools-develop/lib/python2.7/site-packages (from wstools)
Downloading/unpacking six (from wstools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: wstools, six
  Running setup.py install for wstools
    
Successfully installed wstools six
Cleaning up...
```

**Comment by cdonati** [comment]
Thanks, @ssbarnea. The `develop` branch works for me. I was using Python 2.7.12 on Linux.
